services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 3000:80
    links:
      - db

  broker:
    image: ochom/mpesa-broker:latest
    ports:
      - 8080:8080
    environment:
      - name=value
